swagger: '2.0'
################################################################################
#                              API Information                                 #
################################################################################
info:
  version: 1.0
  title: Order Transaction API
  description: |
    This is specification for Order Transaction API
  contact:
    name: Dedy Prasetiady
    email: dedy.berastagi@gmail.com
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Order
  - name: Customer
################################################################################
#                                   Paths                                      #
################################################################################
paths:
  # Customer Path
  /customer/{customer_id}/cart:
    x-api-first-handler: "v1.yaml.Customer.cart"
    get:
      tags:
        - Customer
      description: |
        Return shopping cart id based on customer id ( shopping cart is order
        that has not yet been completed). Create new order if user exist but
        shopping cart not found.
      parameters:
        - name: customer_id
          type: string
          in: path
          required: true
      responses:
        200:
          description: OK
  /customer/{customer_id}/orders:
    x-api-first-handler: "v1.yaml.Customer.orders"
    get:
      tags:
        - Customer
      description: |
        Return array of order id based on customer id.
      parameters:
        - name: customer_id
          type: string
          in: path
          required: true
      responses:
        200:
          description: OK
  # Order Path
  /order/{order_id}:
    x-api-first-handler: "v1.yaml.Order.order"
    get:
      tags:
        - Order
      description: Return order details
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/lineItem:
    x-api-first-handler: "v1.yaml.Order.lineItem"
    post:
      tags:
        - Order
      description: Add product to an order
      parameters:
        - name: order_id
          type: integer
          format: int32
          in: path
          required: true
        - name: product_id
          in: body
          schema:
            type: integer
            format: int32
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/coupon:
    x-api-first-handler: "v1.yaml.Order.coupon"
    post:
      tags:
        - Order
      description: Apply coupon to an order
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
        - name: coupon_code
          in: body
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/checkout:
    x-api-first-handler: "v1.yaml.Order.checkout"
    put:
      tags:
        - Order
      description: Submit order (checkout)
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
        - name: shipping_address
          in: body
          schema:
            $ref: "#/definitions/ShippingAddress"
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/paymentProff:
    x-api-first-handler: "v1.yaml.Order.paymentProff"
    post:
      tags:
        - Order
      description: Pay order, submit payment proff
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
        - name: payment_proff
          in: body
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/verify:
    x-api-first-handler: "v1.yaml.Order.verify"
    put:
      tags:
        - Order
      description: Verify Order
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/ship:
    x-api-first-handler: "v1.yaml.Order.ship"
    put:
      tags:
        - Order
      description: Ship Order
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
      responses:
        200:
          description: OK
  /order/{order_id}/cancel:
    x-api-first-handler: "v1.yaml.Order.cancel"
    put:
      tags:
        - Order
      description: Cancel Order
      parameters:
        - name: order_id
          in: path
          type: integer
          format: int32
          required: true
      responses:
        200:
          description: OK
################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  ShippingAddress:
    required:
      - name
      - phone_number
      - email
      - address
    properties:
      name:
        type: string
      phone_number:
        type: string
      email:
        type: string
        format: email
      address:
        type: string
  ErrorModel:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
